dado_user = input('Digite algo: ')
#print('O tipo deste valor é', type(dado_user))
#print('Só tem espaço?', dado_user.isspace())
#print('É um número?', dado_user.isnumeric())
#print('É alfabético?', dado_user.isalpha())
#print('Está escrito em maiúscula?', dado_user.isupper())
#print('Está escrito em minúscula?', dado_user.islower())
#print('Está capitalizada?', dado_user.istitle())
print(f'O tipo primitivo desse valor é {type(dado_user)}')
print(f'Só tem espaços? {dado_user.isspace()}')
print(f'É um número? {dado_user.isnumeric()}')
print(f'É alfabético? {dado_user.isalpha()}')
print(f'É alfanumérico? {dado_user.isalnum()}')
print(f'Está em maiúsculas? {dado_user.isupper()}')
print(f'Está em minúsculas? {dado_user.islower()}')
print(f'Está capitalizado? {dado_user.istitle()}')
